language: rust

before_install:
    - sudo apt-get install libsuitesparse-dev

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly

script:
    - rustc --version
    - cargo --version
    - cargo test --all --verbose
    - cargo build
    
notifications:
  email:
    - on_success: change
    - on_failure: always
