language: rust

before_install:
    - sudo apt-get install libsuitesparse-dev

matrix:
  include:
    - rust: stable
      env: RUN_RUSTFMT=true
    - rust: beta
    - rust: nightly

script:
    - rustc --version
    - cargo --version
    - cargo test --all --verbose
    
notifications:
  email:
    - on_success: change
    - on_failure: always
